### ISSUE TITLE
discord.Client 변경요청

### ISSUE THREAD

**Issue by undefined7000** [jjun4341/team.peanut.project#19]
현재 작성해놓은 코드는 cogs(Bot)을 이용하여 작성되어있는데...
discord.Client()좀.. 안쓰면 안될까요...

1. Client보다 빠름.
2. Bot은 Client의 하의 클래스지만 최적화가 됌.
3. on_message 도 같이 사용가능.

**Comment by jjun4341** [comment]
cogs 쓰자고 하시던 분 아니신가
일단 그럼 client 로 바꿀게요
제게도 어렵고 다른분들께도 어려워서

**Comment by undefined7000** [comment]
그냥 client는 on_message인데... 어짜피 Cogs에서도 on_message 가능하니까 그냥 Cogs가 더 낫지 않아요?
Bot에 기능도 사용 가능하고 Client 기능도 사용 가능하고
